# Generated by Django 3.0.2 on 2020-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Song_Name', models.CharField(max_length=50)),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
