# Generated by Django 3.0.1 on 2020-01-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harmonyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
