# Generated by Django 3.0.1 on 2020-01-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Harmonyapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
