# Generated by Django 3.0.2 on 2020-01-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10)),
                ('SongName', models.CharField(max_length=10)),
                ('Lyric', models.TextField()),
            ],
        ),
    ]
